config/routes.rb
GoalTracker::Application.routes.draw do
  resources :goals
  resources :progress_events

  resources :activities

  resources :units

  resources :timeframes

  resources :goal_units

end

app/models/timeframe.rb
class Timeframe < ActiveRecord::Base
end

app/controllers/timeframes_controller.rb
class TimeframesController < ApplicationController
  before_action :set_timeframe, only: [:show, :edit, :update, :destroy]

  # GET /timeframes
  # GET /timeframes.json
  def index
    @timeframes = Timeframe.all
  end

  # GET /timeframes/1
  # GET /timeframes/1.json
  def show
  end

  # GET /timeframes/new
  def new
    @timeframe = Timeframe.new
  end

  # GET /timeframes/1/edit
  def edit
  end

  # POST /timeframes
  # POST /timeframes.json
  def create
    @timeframe = Timeframe.new(timeframe_params)

    respond_to do |format|
      if @timeframe.save
        format.html { redirect_to @timeframe, notice: 'Timeframe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @timeframe }
      else
        format.html { render action: 'new' }
        format.json { render json: @timeframe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timeframes/1
  # PATCH/PUT /timeframes/1.json
  def update
    respond_to do |format|
      if @timeframe.update(timeframe_params)
        format.html { redirect_to @timeframe, notice: 'Timeframe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @timeframe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timeframes/1
  # DELETE /timeframes/1.json
  def destroy
    @timeframe.destroy
    respond_to do |format|
      format.html { redirect_to timeframes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timeframe
      @timeframe = Timeframe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timeframe_params
      params.require(:timeframe).permit(:description)
    end
end

app/helpers/timeframes_helper.rb
module TimeframesHelper
end

app/views/timeframes/_form.html.erb
<%= form_for(@timeframe) do |f| %>
  <% if @timeframe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timeframe.errors.count, "error") %> prohibited this timeframe from being saved:</h2>

      <ul>
      <% @timeframe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timeframes/edit.html.erb
<h1>Editing timeframe</h1>

<%= render 'form' %>

<%= link_to 'Show', @timeframe %> |
<%= link_to 'Back', timeframes_path %>

app/views/timeframes/index.html.erb
<h1>Listing timeframes</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @timeframes.each do |timeframe| %>
      <tr>
        <td><%= timeframe.description %></td>
        <td><%= link_to 'Show', timeframe %></td>
        <td><%= link_to 'Edit', edit_timeframe_path(timeframe) %></td>
        <td><%= link_to 'Destroy', timeframe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timeframe', new_timeframe_path %>

app/views/timeframes/new.html.erb
<h1>New timeframe</h1>

<%= render 'form' %>

<%= link_to 'Back', timeframes_path %>

app/views/timeframes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @timeframe.description %>
</p>

<%= link_to 'Edit', edit_timeframe_path(@timeframe) %> |
<%= link_to 'Back', timeframes_path %>