config/routes.rb
GoalTracker::Application.routes.draw do
  resources :goals
  resources :progress_events

  resources :activities

  resources :units

  resources :timeframes

  resources :goal_units

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :activity
  belongs_to :unit
  belongs_to :timeframe
  has_many :progress_events

  def as_json(options={})
    {
      :id => id,
      :activity => activity.description,
      :measurement => "#{measurement} #{unit.description}",
      :timeframe => timeframe.description
    }
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    goals = Goal.all
    
    render :json => goals.as_json, :status => 201
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    puts goal_params
    m, u = params[:measurement].split(' ')
    @activity = Activity.find_or_create_by(description: params[:activity])
    @timeframe = Timeframe.find_or_create_by(description: params[:timeframe])
    @unit = Unit.find_or_create_by(description: u)
    @goal = Goal.new(activity: @activity, timeframe: @timeframe, unit: @unit, measurement: m)
    
    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render status: :created, json: @goal.as_json }
      else
        format.html { render action: 'new' }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url }
      format.json { head :no_content }
    end
  end

  def create_activity
    put params
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.permit(:activity, :measurement, :timeframe)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :activity_id %><br>
    <%= f.text_field :activity_id %>
  </div>
  <div class="field">
    <%= f.label :unit_id %><br>
    <%= f.text_field :unit_id %>
  </div>
  <div class="field">
    <%= f.label :timeframe_id %><br>
    <%= f.text_field :timeframe_id %>
  </div>
  <div class="field">
    <%= f.label :measurement %><br>
    <%= f.number_field :measurement %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<h1>Editing goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<h1>Listing goals</h1>

<table>
  <thead>
    <tr>
      <th>Activity</th>
      <th>Unit</th>
      <th>Timeframe</th>
      <th>Measurement</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.activity %></td>
        <td><%= goal.unit %></td>
        <td><%= goal.timeframe %></td>
        <td><%= goal.measurement %></td>
        <td><%= link_to 'Show', goal %></td>
        <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
        <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal', new_goal_path %>

app/views/goals/new.html.erb
<h1>New goal</h1>

<%= render 'form' %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Activity:</strong>
  <%= @goal.activity %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @goal.unit %>
</p>

<p>
  <strong>Timeframe:</strong>
  <%= @goal.timeframe %>
</p>

<p>
  <strong>Measurement:</strong>
  <%= @goal.measurement %>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>